name: menu_button
description: A menu button widget to select an item in a dropdown list easily customizable
homepage: https://github.com/huextrat/menu_button
version: 1.4.2+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter